version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file: ".test.env"
    volumes:
      - aithc-test-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  aithc-test-data: