"""course

Revision ID: 2504c51722b5
Revises: e967288e19c5
Create Date: 2024-07-09 19:27:23.025544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2504c51722b5'
down_revision: Union[str, None] = 'e967288e19c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('limits', sa.Integer(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('implementer', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('name', name=op.f('uq_courses_name'))
    )
    op.create_table('course_periods',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('period_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_periods_course_id_courses')),
    sa.PrimaryKeyConstraint('course_id', 'period_name', name=op.f('pk_course_periods'))
    )
    op.create_table('course_roles',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_roles_course_id_courses')),
    sa.PrimaryKeyConstraint('course_id', 'role_name', name=op.f('pk_course_roles'))
    )
    op.create_table('course_runs',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_runs_course_id_courses')),
    sa.PrimaryKeyConstraint('course_id', 'run_name', name=op.f('pk_course_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_runs')
    op.drop_table('course_roles')
    op.drop_table('course_periods')
    op.drop_table('courses')
    # ### end Alembic commands ###
