"""course_run_timetable

Revision ID: 68cc9f3338b1
Revises: b85ab4c1beaf
Create Date: 2024-08-20 02:29:13.091042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cc9f3338b1'
down_revision: Union[str, None] = 'b85ab4c1beaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_runs_',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_archive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_runs_')),
    sa.UniqueConstraint('course_id', 'name', name='uix_course_id_name')
    )
    op.create_table('timetable_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_period_date', sa.Date(), nullable=False),
    sa.Column('end_period_date', sa.Date(), nullable=False),
    sa.Column('weekdays', sa.String(), nullable=True),
    sa.Column('course_run_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable_rules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable_rules')
    op.drop_table('course_runs_')
    # ### end Alembic commands ###
