"""rating for feedback

Revision ID: b85ab4c1beaf
Revises: b1ecf9cd86c0
Create Date: 2024-07-30 20:05:29.798664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85ab4c1beaf'
down_revision: Union[str, None] = 'b1ecf9cd86c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('rating', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'rating')
    # ### end Alembic commands ###
